### PR TITLE
feat: Refactor create database options schema to accept array

### LINKED ISSUE #1575: schema field in CreateDatabaseOptions does not allow string[].
#### Environment details

  - `@google-cloud/spanner` version: 5.16.3

#### Details

The type of the schema field in `CreateDatabaseOptions` is `string`, but reading the [tutorial](https://cloud.google.com/spanner/docs/getting-started/nodejs#look_through_sample_files) and the [internal logic](https://github.com/googleapis/nodejs-spanner/blob/8b950b3af8a66be6c27b5482611e116853d23ecf/src/instance.ts#L842-L845), `string[]` should also be allowed.
So I am wondering if I can define it as string | string[]?
I'm assuming the following modification
https://github.com/googleapis/nodejs-spanner/commit/00f9e7c05c7e474be4d9abadb1e18d244be52877

### PR DESCRIPTION
**Pull request by asthamohta**

### CODE REVIEW

**Review by vi3k6i5 — APPROVED** [review]
LGTM

**Comment by asthamohta** [comment]
Hi @winor30 Could you update the branch and I will merge it

**Review by olavloite — APPROVED** [review]

**Comment by winor30** [comment]
@asthamohta 

https://github.com/googleapis/nodejs-spanner/pull/1578#issuecomment-1060199134

PR updates have been completed.

**Comment by asthamohta** [comment]
@winor30 the change will be available in the next release. Thanks a ton!

**Pull request merged**
