### PR TITLE
refactor: return GoogleError instead of Error in handwritten library.

### PR DESCRIPTION
**Pull request by rajatbhatta**
- Replacing Error by [GoogleError](https://github.com/googleapis/gax-nodejs/blob/main/src/googleError.ts) for making the error consistent across all GAPIC libraries.

### CODE REVIEW

**Review by summer-ji-eng — APPROVED** [review]
LGTM, thanks for working on this.

**Comment by summer-ji-eng** [comment]
LGTM, let's wait see any comment from the spanner experts.

**Review by asthamohta — APPROVED** [review]
LGTM

**Comment by ansh0l** [comment]
Adding DoNotmege label pending final review from Knut.

**Review by olavloite — APPROVED** [review]
LGTM

**Pull request merged**
