### PR TITLE
Fix color highlighting in CHANGELOG.md

### PR DESCRIPTION
**Pull request by WaldoJeffers**
Clearly not a very significant PR 😅 The devil is in the detail I guess

- [x] Tests and linter pass
- [ ] ~Code coverage does not decrease (if any source code was changed)~
- [ ] ~Appropriate docs were updated (if necessary)~

### CODE REVIEW

**Comment by WaldoJeffers** [comment]
I signed it!

**Comment by stephenplusplus** [comment]
Nice!

@JustinBeckwith can we make manual edits to the CHANGELOG?

**Comment by JustinBeckwith** [comment]
Yeah I think that should be fine.  Thanks for the fix!

**Comment by WaldoJeffers** [comment]
You're welcome, it didn't take me too long 😬 Congrats for v2

**Pull request merged**
