### PR TITLE
Support {{projectId}} replacement.

### PR DESCRIPTION
**Pull request by stephenplusplus**
#### To Dos

- Unit Tests
  - [x] database.js
  - [x] index.js
  - [x] instance.js
  - [x] session-pool.js
  - [x] session.js
  - [x] transaction-request.js
  - [x] transaction.js

### CODE REVIEW

**Comment by lukesneeringer** [comment]
@stephenplusplus In light of @jmdobry's changes, can you resolve the conflicts (which should make tests pass)?

**Comment by lukesneeringer** [comment]
Okay, I made a tactical error here. I really should have merged this first.

Sorry @stephenplusplus; I created work for you.

**Comment by stephenplusplus** [comment]
That's okay!

**Comment by lukesneeringer** [comment]
As a note, you still have conflicts. Not sure if you are aware or not. :-)

**Pull request merged**
