### PR TITLE
fix query param types bug

### LINKED ISSUE #42: select with empty array parameters
OS: Mac OSX 10.13.1
Node.js version: 8.9.1
npm version: 5.5.1
version: 0.8.0

simple query:

```
tx.run({
                    sql: `SELECT * FROM Goods WHERE goodId in UNNEST(@goodIds)`,
                    params: {
                        goodIds: [],
                    }
}
```
return error:

```
req.url - http://retail.gss.local:9002/api/goods-documents/upsert
InternalServerError: err.code: 3
err.message: The code field is required for types.
err.status: undefined
err.stack: Error: The code field is required for types.
    at ClientReadableStream._emitStatusIfDone (/Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/grpc/src/node/src/client.js:209:19)
    at ClientReadableStream._receiveStatus (/Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/grpc/src/node/src/client.js:188:8)
    at /Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/grpc/src/node/src/client.js:600:14
err location:
GoodsDocument.upsert\select...GoodsDocuments...rollback...
data:
{"document":{"organizationId":999,"documentId":1,"date":1511357040129,"number":"1","transactionType":1,"subject":"სატესტო საბუთი","stockId":1,"receivedStockId":2,"accomplished":true,"timestamp":1511357072148,"shardId":3},"transactions":[]}
apiResponse:
{}
    at Function.dbUtils.getDsError (/Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/dbUtils.js:218:16)
    at error (/Users/Chipintoza/GSS Projects/retail.gss.ge/server/tables/goods-documents-table.js:273:64)
    at tx.rollback (/Users/Chipintoza/GSS Projects/retail.gss.ge/server/tables/goods-documents-table.js:306:32)
    at /Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/transaction.js:456:5
    at /Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/transaction.js:329:7
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### LINKED ISSUE #43: select with array parameters
OS: Mac OSX 10.13.1
Node.js version: 8.9.1
npm version: 5.5.1
version: 0.8.0

there is also some errors:
in transaction.js
[var child;](https://github.com/googleapis/nodejs-spanner/blob/ca0f55b0ccb595519b18ab6ed4b6920aeccdd05a/src/transaction.js#L725)

it must be initialised:
`var child = undefined;`

if in params first property is array all rest properties becomes array 

same is in database.js
```
var childType;
var child;

```
this two files has difference logic and is this right?

because of this I'm forced define types :(

@stephenplusplus  I see follow-up comment !!!

### PR DESCRIPTION
**Pull request by callmehiphop**
Fixes #42 
Fixes #43

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Fixes #43 as well, right?

**Comment by callmehiphop** [comment]
@stephenplusplus yep, I hadn't noticed a second bug was opened.

**Comment by walshie4** [comment]
Where is this documented?  Couldn't find anything near `IN` usage or similar

**Comment by stephenplusplus** [comment]
We have a huge problem with docs :( https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2783

**Pull request merged**
