### PR TITLE
Fix issue with samples where data is inserted wrong.

### PR DESCRIPTION
**Pull request by jmdobry**

### CODE REVIEW

**Comment by jmdobry** [comment]
Not sure why lint failed, I can't get CircleCI to load. It passes for me locally.

**Comment by jmdobry** [comment]
Can someone re-trigger the failing builds?

**Comment by lukesneeringer** [comment]
Yeah, I can (and I will figure out how to make it so you can).

CI failed because `repo-tools: Permission denied`. This happens about 5% of the time for some reason that I have not yet determined. It seems to only happen on lint.

**Comment by jmdobry** [comment]
Can someone retry the failing appveyor build?

**Comment by stephenplusplus** [comment]
Rebuild clicked.

**Pull request merged**
